excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://richardblewellen.github.io
title: richardblewellen
tagline: A log of everyday life
description: My awesome new site
paginate: 5